version: "3.8"

services:
  products:
    image: semirm/myt-products:1
    build:
      context: .
      dockerfile: cmd/product/Dockerfile
    container_name: myt_products
    command:
      - -discounts_uri=myt_discounts:8002
    ports:
      - "8001:8001"
    depends_on:
      - discounts
    networks:
      - myt
  discounts:
    image: semirm/myt-discounts:1
    build:
      context: .
      dockerfile: cmd/discount/Dockerfile
    container_name: myt_discounts
    ports:
      - "8002:8002"
    networks:
      - myt
  gateway:
    image: semirm/myt-gateway:1
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    container_name: myt_gateway
    command:
      - -products_uri=myt_products:8001
      - -usr=default
      - -pwd=default
    ports:
      - "8000:8000"
    depends_on:
      - products
    networks:
      - myt
networks:
  myt: